### ISSUE TITLE
API Call response != 201

### ISSUE THREAD

**Issue by vict0rsch** [mlco2/codecarbon#204]
* CodeCarbon version: branch `api_cli`
* Python version: 3.9.2
* Operating System: macOS

## Code

```
from __future__ import print_function
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.optim.lr_scheduler import StepLR

from codecarbon import track_emissions


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, 3, 1)
        self.conv2 = nn.Conv2d(32, 64, 3, 1)
        self.dropout1 = nn.Dropout(0.25)
        self.dropout2 = nn.Dropout(0.5)
        self.fc1 = nn.Linear(9216, 128)
        self.fc2 = nn.Linear(128, 10)

    def forward(self, x):
        x = self.conv1(x)
        x = F.relu(x)
        x = self.conv2(x)
        x = F.relu(x)
        x = F.max_pool2d(x, 2)
        x = self.dropout1(x)
        x = torch.flatten(x, 1)
        x = self.fc1(x)
        x = F.relu(x)
        x = self.dropout2(x)
        x = self.fc2(x)
        output = F.log_softmax(x, dim=1)
        return output


def train(model, device, train_loader, optimizer, epoch, log_interval):
    model.train()
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()
        output = model(data)
        loss = F.nll_loss(output, target)
        loss.backward()
        optimizer.step()
        if batch_idx % log_interval == 0:
            print(" " * 100, end="\r")
            print(
                "Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}".format(
                    epoch,
                    batch_idx * len(data),
                    len(train_loader.dataset),
                    100.0 * batch_idx / len(train_loader),
                    loss.item(),
                ),
            )


def test(model, device, test_loader):
    model.eval()
    test_loss = 0
    correct = 0
    with torch.no_grad():
        for data, target in test_loader:
            data, target = data.to(device), target.to(device)
            output = model(data)
            test_loss += F.nll_loss(
                output, target, reduction="sum"
            ).item()  # sum up batch loss
            pred = output.argmax(
                dim=1, keepdim=True
            )  # get the index of the max log-probability
            correct += pred.eq(target.view_as(pred)).sum().item()

    test_loss /= len(test_loader.dataset)

    print(
        "\nTest set: Average loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n".format(
            test_loss,
            correct,
            len(test_loader.dataset),
            100.0 * correct / len(test_loader.dataset),
        )
    )


@track_emissions(
    project_name="train-mnist",
    measure_power_secs=10,
    save_to_api=True,
    save_to_file=True,
    co2_signal_api_token="8cd6bb15612baf94",
)
def main():

    use_cuda = torch.cuda.is_available()

    torch.manual_seed(123)

    device = torch.device("cuda" if use_cuda else "cpu")

    train_kwargs = {"batch_size": 64}
    test_kwargs = {"batch_size": 128}
    if use_cuda:
        cuda_kwargs = {"num_workers": 1, "pin_memory": True, "shuffle": True}
        train_kwargs.update(cuda_kwargs)
        test_kwargs.update(cuda_kwargs)

    transform = transforms.Compose(
        [transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,))]
    )
    dataset1 = datasets.MNIST("../data", train=True, download=True, transform=transform)
    dataset2 = datasets.MNIST("../data", train=False, transform=transform)
    train_loader = torch.utils.data.DataLoader(dataset1, **train_kwargs)
    test_loader = torch.utils.data.DataLoader(dataset2, **test_kwargs)

    model = Net().to(device)
    optimizer = optim.Adadelta(model.parameters(), lr=1e-3)

    scheduler = StepLR(optimizer, step_size=1, gamma=0.7)
    for epoch in range(1, 2):
        train(model, device, train_loader, optimizer, epoch, 10)
        test(model, device, test_loader)
        scheduler.step()


if __name__ == "__main__":
    main()
```

## Reproduce:

```
python train_mnist.py
```

Stop after a few seconds

Then:

```
Train Epoch: 1 [21120/60000 (35%)]      Loss: 2.144908                                              
^C[codecarbon INFO @ 12:47:07] 
Graceful stopping: collecting and writing information.
Please Allow for a few seconds...
2021-06-30T12:47:10.224305+02:00
2021-06-30T12:47:11.892079+02:00
[codecarbon ERROR @ 12:47:12]  Error when calling the API with : {"timestamp": "2021-06-30T12:47:11.892079+02:00", "run_id": "30b57048-5a00-4d74-827f-c6e6ad07d9ba", "duration": 1, "emissions": 0.0, "energy_consumed": 0.0}
[codecarbon ERROR @ 12:47:12]  API return http code 422 and answer : {"detail":[{"loc":["body","emissions"],"msg":"ensure this value is greater than 0","type":"value_error.number.not_gt","ctx":{"limit_value":0}},{"loc":["body","energy_consumed"],"msg":"ensure this value is greater than 0","type":"value_error.number.not_gt","ctx":{"limit_value":0}}]}
[codecarbon ERROR @ 12:47:12] 
Traceback (most recent call last):
  File "/Users/victor/Documents/Github/mlco2/code-carbon/codecarbon/emissions_tracker.py", line 608, in wrapped_fn
    fn(*args, **kwargs)
  File "/Users/victor/Documents/DataForGood/demo/train_mnist.py", line 123, in main
    train(model, device, train_loader, optimizer, epoch, 10)
  File "/Users/victor/Documents/DataForGood/demo/train_mnist.py", line 45, in train
    loss.backward()
  File "/Users/victor/.pyenv/versions/3.9.2/lib/python3.9/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/Users/victor/.pyenv/versions/3.9.2/lib/python3.9/site-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/victor/Documents/Github/mlco2/code-carbon/codecarbon/core/api_client.py", line 77, in add_emission
    assert r.status_code == 201
AssertionError
[codecarbon INFO @ 12:47:12] Done!

Traceback (most recent call last):
  File "/Users/victor/Documents/DataForGood/demo/train_mnist.py", line 129, in <module>
    main()
  File "/Users/victor/Documents/Github/mlco2/code-carbon/codecarbon/emissions_tracker.py", line 608, in wrapped_fn
    fn(*args, **kwargs)
  File "/Users/victor/Documents/DataForGood/demo/train_mnist.py", line 123, in main
    train(model, device, train_loader, optimizer, epoch, 10)
  File "/Users/victor/Documents/DataForGood/demo/train_mnist.py", line 45, in train
    loss.backward()
  File "/Users/victor/.pyenv/versions/3.9.2/lib/python3.9/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/Users/victor/.pyenv/versions/3.9.2/lib/python3.9/site-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
KeyboardInterrupt
```

**Comment by benoit-cty** [comment]
Hello,
As the log said : "emissions"],"msg":"ensure this value is greater than 0"
We do not expect emissions to be zero.

Things we could do:
- Remove the assert to avoid the stacktrace and made the log message more visible
- Check the values before calling the API
- Allow 0 value in the API : but I will prefere to continue to deny this as it is useless if all values is at zero.

**Comment by benoit-cty** [comment]
In https://github.com/mlco2/codecarbon/pull/202 I've removed the assert  to avoid the stacktrace and made the log message more visible.
