### ISSUE TITLE
root only perms file-related crash: /sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj

### ISSUE THREAD

**Issue by stas00** [mlco2/codecarbon#232]
* CodeCarbon version: master
* Python version: 3.8
* Operating System: Ubuntu 20.04

### Description

```
[codecarbon INFO @ 15:19:53] Unable to read Intel RAPL files at [RAPLFile(name='Processor Power_0(Watt)', path='/sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj', energy_reading=Energy(kwh=0), power_measurement=0)]
                 Exception occurred [Errno 13] Permission denied: '/sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj'
Traceback (most recent call last):
  File "/mnt/nvme1/code/huggingface/codecarbon-bs/codecarbon/core/cpu.py", line 200, in get_cpu_details
    list(map(lambda rapl_file: rapl_file.start(), self._rapl_files))
  File "/mnt/nvme1/code/huggingface/codecarbon-bs/codecarbon/core/cpu.py", line 200, in <lambda>
    list(map(lambda rapl_file: rapl_file.start(), self._rapl_files))
  File "/mnt/nvme1/code/huggingface/codecarbon-bs/codecarbon/core/rapl.py", line 22, in start
    self.energy_reading = self._get_value()
  File "/mnt/nvme1/code/huggingface/codecarbon-bs/codecarbon/core/rapl.py", line 17, in _get_value
    with open(self.path, "r") as f:
PermissionError: [Errno 13] Permission denied: '/sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj'
```

On another system this file is readable by users:
```
l /sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj
-r--r--r-- 1 root root 4.0K Jul 20 10:06 /sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj
```

On mine it's:
```
l /sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj
-r-------- 1 root root 4.0K Jul 24 15:06 /sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj
```

I can manually fix it, but on the next reboot it goes back to root-only `r` perms.

Here is a wider net:
```
l /sys/class/powercap/intel-rapl/intel-rapl:0/
total 0
-r-------- 1 root root 4.0K Jul 24 15:10 constraint_0_max_power_uw
-r-------- 1 root root 4.0K Jul 24 15:10 constraint_0_name
-rw------- 1 root root 4.0K Jul 24 15:10 constraint_0_power_limit_uw
-rw------- 1 root root 4.0K Jul 24 15:10 constraint_0_time_window_us
-r-------- 1 root root 4.0K Jul 24 15:10 constraint_1_max_power_uw
-r-------- 1 root root 4.0K Jul 24 15:10 constraint_1_name
-rw------- 1 root root 4.0K Jul 24 15:10 constraint_1_power_limit_uw
-rw------- 1 root root 4.0K Jul 24 15:10 constraint_1_time_window_us
lrwxrwxrwx 1 root root    0 Jul 24 15:10 device -> ../../intel-rapl/
-rw-r--r-- 1 root root 4.0K Jul 24 15:10 enabled
-r-------- 1 root root 4.0K Jul 24 15:06 energy_uj
drwxr-xr-x 3 root root    0 Jul 24 15:10 intel-rapl:0:0/
drwxr-xr-x 3 root root    0 Jul 24 15:10 intel-rapl:0:1/
-r-------- 1 root root 4.0K Jul 24 15:10 max_energy_range_uj
-r--r--r-- 1 root root 4.0K Jul 24 15:06 name
drwxr-xr-x 2 root root    0 Jul 24 15:10 power/
lrwxrwxrwx 1 root root    0 Jul 24 15:10 subsystem -> ../../../../../class/powercap/
-rw-r--r-- 1 root root 4.0K Jul 24 15:10 uevent
```

Thanks.

**Comment by benoit-cty** [comment]
That is strange because according to http://web.eece.maine.edu/~vweaver/projects/rapl/ `Reading the files under /sys/class/powercap/intel-rapl/intel-rapl:0 [...] requires no special permissions, and was introduced in Linux 3.13`
The other machine is also Ubuntu 20.04 ?

**Comment by stas00** [comment]
More precise it's Kubuntu, but it should be the same on the system level as Ubuntu
```
$ uname -a
Linux hope 5.4.0-80-generic ...
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

The one where the read perms are set to all is RedHatEnterprise 8.1.

**Comment by benoit-cty** [comment]
Very bad news for Code Carbon : I now have the same problem on Debian server at work.
We are not alone : https://github.com/prometheus/node_exporter/issues/1892

There is a workaround:
add this to `/etc/sysfs.conf`:
`mode class/powercap/intel-rapl:0/energy_uj = 0444`

But it mean our user need root access at least one time to do it or ask for it to the IT team :cry:

**Comment by benoit-cty** [comment]
I've made a new issue to find a better workaround https://github.com/mlco2/codecarbon/issues/244
