### ISSUE TITLE
more shutdown issues

### ISSUE THREAD

**Issue by stas00** [mlco2/codecarbon#260]
* CodeCarbon version: master
* Python version: 3.8
* Operating System: Ubuntu

In addition to the reported https://github.com/mlco2/codecarbon/issues/251 I get 2 more issues during shutdown (w/o the traceback):

```
TypeError: __init__() got an unexpected keyword argument 'misfire_grace_time'
AttributeError: 'OfflineEmissionsTracker' object has no attribute '_start_time'
```
these get unnoticed in the huge logs as the exceptions aren't propagated, so it's printed but doesn't break the code.

The full traceback (2 gpus):

```
[codecarbon INFO @ 20:37:39] offline tracker init
[codecarbon WARNING @ 20:37:39] graceful shutdown. Exceptions:
[codecarbon WARNING @ 20:37:39] <class 'Exception'>
Traceback (most recent call last):
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/codecarbon/core/util.py", line 18, in suppress
    yield
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/codecarbon/emissions_tracker.py", line 658, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'misfire_grace_time'
[codecarbon WARNING @ 20:37:39] stopping.
[codecarbon INFO @ 20:37:39] offline tracker init
[codecarbon WARNING @ 20:37:39] graceful shutdown. Exceptions:
[codecarbon WARNING @ 20:37:39] <class 'Exception'>
Traceback (most recent call last):
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/codecarbon/core/util.py", line 18, in suppress
    yield
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/codecarbon/emissions_tracker.py", line 658, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'misfire_grace_time'
[codecarbon WARNING @ 20:37:39] stopping.
[W ProcessGroupNCCL.cpp:1569] Rank 1 using best-guess GPU 1 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
[W ProcessGroupNCCL.cpp:1569] Rank 0 using best-guess GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
[codecarbon WARNING @ 20:37:44] graceful shutdown. Exceptions:
[codecarbon WARNING @ 20:37:44] graceful shutdown. Exceptions:
[codecarbon WARNING @ 20:37:44] <class 'Exception'>
Traceback (most recent call last):
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/codecarbon/core/util.py", line 18, in suppress
    yield
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/codecarbon/emissions_tracker.py", line 359, in start
    if self._start_time is not None:
AttributeError: 'OfflineEmissionsTracker' object has no attribute '_start_time'
[codecarbon WARNING @ 20:37:44] <class 'Exception'>
Traceback (most recent call last):
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/codecarbon/core/util.py", line 18, in suppress
    yield
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/codecarbon/emissions_tracker.py", line 359, in start
    if self._start_time is not None:
AttributeError: 'OfflineEmissionsTracker' object has no attribute '_start_time'
[codecarbon WARNING @ 20:37:44] stopping.
[codecarbon WARNING @ 20:37:44] stopping.
```

The setup is the same as in: AttributeError: 'OfflineEmissionsTracker' object has no attribute '_start_time'

**Comment by benoit-cty** [comment]
Hi @stas00 , 'misfire_grace_time' was added for debugging APScheduler. As I have removed APScheduler, I have removed 'misfire_grace_time' and 'max_instances' parameters.
Can you try again after removing 'misfire_grace_time' and 'max_instances' ?

**Comment by stas00** [comment]
I switched to master and removed `max_instances` - no problem

once I remove `misfire_grace_time` everything becomes super sluggish and shutting down takes forever.

Secondly it somehow impacts the test suite which uses asyncio which now hangs in:
```
    select (selectors.py:468)
    _run_once (asyncio/base_events.py:1823)
    run_forever (asyncio/base_events.py:570)
    run_until_complete (asyncio/base_events.py:603)
```

So if I run the program normally it just becomes extremely slow around shutdown.

If I run it in the test suite which uses asyncio to communicate with the external processes it hangs.

So the python scheduler isn't working well and it somehow interferes with asyncio library.

Moreover once I got:

```
stderr: Traceback (most recent call last):
stderr:   File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/threading.py", line 932, in _bootstrap_inner
stderr:     self.run()
stderr:   File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/threading.py", line 1254, in run
stderr:     self.function(*self.args, **self.kwargs)
stderr:   File "/mnt/nvme1/code/huggingface/codecarbon/codecarbon/external/scheduler.py", line 41, in _run
stderr:     self.function(*self.args, **self.kwargs)
stderr:   File "/mnt/nvme1/code/huggingface/codecarbon/codecarbon/emissions_tracker.py", line 521, in _measure_power_and_energy
stderr:     power, energy = hardware.measure_power_and_energy(
stderr:   File "/mnt/nvme1/code/huggingface/codecarbon/codecarbon/external/hardware.py", line 155, in measure_power_and_energy
stderr:     power = Power.from_energy_delta_and_delay(energy, last_duration)
stderr:   File "/mnt/nvme1/code/huggingface/codecarbon/codecarbon/core/units.py", line 124, in from_energy_delta_and_delay
stderr: Exception in thread Thread-6:
stderr: Traceback (most recent call last):
stderr:   File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/threading.py", line 932, in _bootstrap_inner
stderr:     return cls.from_energies_and_delay(e, Energy(0), delay)
stderr:   File "/mnt/nvme1/code/huggingface/codecarbon/codecarbon/core/units.py", line 119, in from_energies_and_delay
stderr:     kW = delta_energy / delay.hours
stderr: AttributeError: 'float' object has no attribute 'hours'
stderr:     self.run()
stderr:   File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/threading.py", line 1254, in run
stderr:     self.function(*self.args, **self.kwargs)
stderr:   File "/mnt/nvme1/code/huggingface/codecarbon/codecarbon/external/scheduler.py", line 41, in _run
stderr:     self.function(*self.args, **self.kwargs)
stderr:   File "/mnt/nvme1/code/huggingface/codecarbon/codecarbon/emissions_tracker.py", line 521, in _measure_power_and_energy
stderr:     power, energy = hardware.measure_power_and_energy(
stderr:   File "/mnt/nvme1/code/huggingface/codecarbon/codecarbon/external/hardware.py", line 155, in measure_power_and_energy
stderr:     power = Power.from_energy_delta_and_delay(energy, last_duration)
stderr:   File "/mnt/nvme1/code/huggingface/codecarbon/codecarbon/core/units.py", line 124, in from_energy_delta_and_delay
stderr:     return cls.from_energies_and_delay(e, Energy(0), delay)
stderr:   File "/mnt/nvme1/code/huggingface/codecarbon/codecarbon/core/units.py", line 119, in from_energies_and_delay
stderr:     kW = delta_energy / delay.hours
stderr: AttributeError: 'float' object has no attribute 'hours'
```

I'm pretty ready to give up on trying to make this product work for us :(

**Comment by benoit-cty** [comment]
Closing old issue, please re-open if needed.
