### ISSUE TITLE
Unsupported Nvidia GPU on Windows

### ISSUE THREAD

**Issue by h-sdl** [mlco2/codecarbon#295]
* CodeCarbon version: latest
* Python version: 3.9.7
* Operating System: Windows 10

### Description

As noticed by @benoit-cty, my GPU is unsupported by codecarbon (4-year-old Nvidia GeForce 940MX on Windows 10). I don't know whether this is expected (too old and laptop GPU?) of not. Consequently, reported consumed power is 0 at all times.

```
>>> codecarbon monitor
[...]
[codecarbon DEBUG @ 13:35:08] CPU : 17.10 W during 10.01 s [measurement time: 3.4070]
[codecarbon INFO @ 13:35:08] 0.000040 kWh of electricity used since the begining.
[codecarbon INFO @ 13:35:13] Energy consumed for all RAM : 0.000040 kWh
[codecarbon DEBUG @ 13:35:13] RAM : 4.79 W during 4.83 s [measurement time: 0.0000]
[codecarbon DEBUG @ 13:35:13] Failed to retrieve gpu information
Traceback (most recent call last):
  File "d:\documents\d4g\codecarbon_git\codecarbon\core\gpu.py", line 190, in get_gpu_details
    "power_usage": get_power_usage(handle),
  File "d:\documents\d4g\codecarbon_git\codecarbon\core\gpu.py", line 68, in get_power_usage
    return pynvml.nvmlDeviceGetPowerUsage(handle)
  File "D:\Dev\Anaconda3\envs\codecarbon\lib\site-packages\pynvml\nvml.py", line 2032, in nvmlDeviceGetPowerUsage
    _nvmlCheckReturn(ret)
  File "D:\Dev\Anaconda3\envs\codecarbon\lib\site-packages\pynvml\nvml.py", line 765, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.nvml.NVMLError_NotSupported: Not Supported
[codecarbon INFO @ 13:35:13] Energy consumed for all GPUs : 0.000046 kWh
[codecarbon DEBUG @ 13:35:13] Failed to retrieve gpu information
Traceback (most recent call last):
  File "d:\documents\d4g\codecarbon_git\codecarbon\core\gpu.py", line 190, in get_gpu_details
    "power_usage": get_power_usage(handle),
  File "d:\documents\d4g\codecarbon_git\codecarbon\core\gpu.py", line 68, in get_power_usage
    return pynvml.nvmlDeviceGetPowerUsage(handle)
  File "D:\Dev\Anaconda3\envs\codecarbon\lib\site-packages\pynvml\nvml.py", line 2032, in nvmlDeviceGetPowerUsage
    _nvmlCheckReturn(ret)
  File "D:\Dev\Anaconda3\envs\codecarbon\lib\site-packages\pynvml\nvml.py", line 765, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.nvml.NVMLError_NotSupported: Not Supported
[codecarbon DEBUG @ 13:35:13] GPU : 0.00 W during 4.83 s [measurement time: 0.5552]
```

**Comment by benoit-cty** [comment]
Is `nvidia-smi` (see https://stackoverflow.com/questions/57100015/how-do-i-run-nvidia-smi-on-windows) working on your computer ?

**Comment by benoit-cty** [comment]
Closing because of lack of answer, feel free to reopen.
