### ISSUE TITLE
Map visualization of "Global Benchmarks" not appearing in dashboard

### ISSUE THREAD

**Issue by ejhusom** [mlco2/codecarbon#306]
* CodeCarbon version: 2.1.0
* Python version: 3.8.10
* Operating System: Ubuntu 20.04

### Description

I used CodeCarbon to create an emissions report `emissions.csv`, and wanted to display this report using `carbonboard`.

### What I Did

I ran my project with the following decorator in order to create a emissions report:

```python
@track_emissions(offline=True, country_iso_code="NOR", project_name="test_project")
def run_project():
   ...
```

The emissions report `emissions.csv` was successfully created, and I attempted to visualize this by running the following command:

```
carbonboard --filepath=emissions.csv
```

When opening the dashboard in the browser, the map visualization of "Global Benchmarks" does not appear, and is replaced by an empty figure as shown here:

![Screenshot from 2022-05-05 12-05-25](https://user-images.githubusercontent.com/42419987/166902616-b155c814-6efa-4025-99f6-ad6f954c6a58.png)

In the command line, the following is printed:

```
27.0.0.1 - - [05/May/2022 12:03:05] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 12:03:05] "GET /_dash-component-suites/dash/deps/polyfill@7.v2_3_1m1651739542.12.1.min.js HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 12:03:05] "GET /_dash-component-suites/dash/deps/react@16.v2_3_1m1651739542.14.0.min.js HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 12:03:05] "GET /_dash-component-suites/dash/deps/react-dom@16.v2_3_1m1651739542.14.0.min.js HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 12:03:05] "GET /_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_3_1m1651739542.min.js HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 12:03:05] "GET /_dash-component-suites/dash/deps/prop-types@15.v2_3_1m1651739542.7.2.min.js HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 12:03:05] "GET /_dash-component-suites/dash_bootstrap_components/_components/dash_bootstrap_components.v0_13_1m1651739860.min.js HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 12:03:05] "GET /_dash-component-suites/dash/dcc/dash_core_components-shared.v2_3_0m1651739542.js HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 12:03:05] "GET /_dash-component-suites/dash/dcc/dash_core_components.v2_3_0m1651739542.js HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 12:03:05] "GET /_dash-component-suites/dash/html/dash_html_components.v2_0_2m1651739542.min.js HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 12:03:05] "GET /_dash-component-suites/dash/dash_table/bundle.v5_1_1m1651739542.js HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 12:03:05] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 12:03:05] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 12:03:05] "GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1" 304 -
127.0.0.1 - - [05/May/2022 12:03:05] "GET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1" 304 -
127.0.0.1 - - [05/May/2022 12:03:05] "GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1" 304 -
/home/erikhu/Documents/Erdre/venv_cc/lib/python3.8/site-packages/codecarbon/viz/data.py:20: FutureWarning:

Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.

127.0.0.1 - - [05/May/2022 12:03:05] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 12:03:06] "GET /_dash-component-suites/dash/dash_table/async-highlight.js HTTP/1.1" 304 -
127.0.0.1 - - [05/May/2022 12:03:06] "GET /_dash-component-suites/dash/dash_table/async-table.js HTTP/1.1" 304 -
127.0.0.1 - - [05/May/2022 12:03:06] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 12:03:06] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 12:03:06] "POST /_dash-update-component HTTP/1.1" 200 -
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/home/erikhu/Documents/Erdre/venv_cc/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/erikhu/Documents/Erdre/venv_cc/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/erikhu/Documents/Erdre/venv_cc/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/erikhu/Documents/Erdre/venv_cc/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/erikhu/Documents/Erdre/venv_cc/lib/python3.8/site-packages/dash/dash.py", line 1383, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/home/erikhu/Documents/Erdre/venv_cc/lib/python3.8/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/home/erikhu/Documents/Erdre/venv_cc/lib/python3.8/site-packages/codecarbon/viz/carbonboard.py", line 150, in update_global_comparisons
    global_emissions_choropleth_data = data.get_global_emissions_choropleth_data(
  File "/home/erikhu/Documents/Erdre/venv_cc/lib/python3.8/site-packages/codecarbon/viz/data.py", line 107, in get_global_emissions_choropleth_data
    country_name = global_energy_mix[country_iso_code]["countryName"]
KeyError: 'countryName'
[codecarbon.viz.carbonboard ERROR @ 12:03:06] Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/home/erikhu/Documents/Erdre/venv_cc/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/erikhu/Documents/Erdre/venv_cc/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/erikhu/Documents/Erdre/venv_cc/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/erikhu/Documents/Erdre/venv_cc/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/erikhu/Documents/Erdre/venv_cc/lib/python3.8/site-packages/dash/dash.py", line 1383, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/home/erikhu/Documents/Erdre/venv_cc/lib/python3.8/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/home/erikhu/Documents/Erdre/venv_cc/lib/python3.8/site-packages/codecarbon/viz/carbonboard.py", line 150, in update_global_comparisons
    global_emissions_choropleth_data = data.get_global_emissions_choropleth_data(
  File "/home/erikhu/Documents/Erdre/venv_cc/lib/python3.8/site-packages/codecarbon/viz/data.py", line 107, in get_global_emissions_choropleth_data
    country_name = global_energy_mix[country_iso_code]["countryName"]
KeyError: 'countryName'
127.0.0.1 - - [05/May/2022 12:03:06] "POST /_dash-update-component HTTP/1.1" 500 -
127.0.0.1 - - [05/May/2022 12:03:06] "GET /assets/house_icon.png HTTP/1.1" 304 -
127.0.0.1 - - [05/May/2022 12:03:06] "GET /assets/car_icon.png HTTP/1.1" 304 -
127.0.0.1 - - [05/May/2022 12:03:06] "GET /assets/tv_icon.png HTTP/1.1" 304 -
127.0.0.1 - - [05/May/2022 12:03:06] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 12:03:06] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 12:03:06] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 12:03:06] "POST /_dash-update-component HTTP/1.1" 200 -
```

The first error relates to the variable `countryName`, which should be changed to `country_name`. Further investigation shows that there also is a problem with the global energy mix being deprecated, and that it is not updated throughout the code for visualization.

**Comment by SaboniAmine** [comment]
Hello! Thanks for noticing this bug!
We appreciate your contribution, that lead us to discover other bugs around country name attributes.

We will merge it in a temporary branch, in order to add the fixes and then add it to master.
