### ISSUE TITLE
Dash app crashes when you clear selection

### ISSUE THREAD

**Issue by dsblank** [mlco2/codecarbon#42]
Dash app crashes when you clear the select list:

![Screenshot from 2020-11-09 11-05-52](https://user-images.githubusercontent.com/168568/98585180-bbae0d80-227b-11eb-86b3-9dbeb110b4c6.png)

```
[2020-11-09 11:05:43,804] ERROR in app: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/home/dblank/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dblank/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dblank/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dblank/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dblank/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dblank/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dblank/.local/lib/python3.8/site-packages/dash/dash.py", line 1059, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/home/dblank/.local/lib/python3.8/site-packages/dash/dash.py", line 994, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "../codecarbon/viz/carbonboard.py", line 77, in update_project_data
    project_summary = data.get_project_summary(project_data.data)
  File "/home/dblank/comet/code-carbon/codecarbon/viz/data.py", line 24, in get_project_summary
    last_run = project_data[-1]
IndexError: list index out of range
```

**Comment by kngoyal** [comment]
Is the csv file empty ? @dsblank

**Comment by dsblank** [comment]
No, it is not empty.

**Comment by kngoyal** [comment]
Unable to replicate this on my end.
