### ISSUE TITLE
Float division by zero on EmissionsTracker start_task

### ISSUE THREAD

**Issue by philippkolbe** [mlco2/codecarbon#627]
* CodeCarbon version: 2.5.0
* Python version: 3.10.14
* Operating System: Windows 11 (can't reproduce it on unix or MacOS!)

### Description

I'm trying to use the `start_task` function to measure different parts of my algorithm seperately. It's failing immideatly with a float division by zero error.

### What I Did

I ran this code:
```python
from codecarbon import EmissionsTracker

# Initialize the emissions tracker
tracker = EmissionsTracker()

# Start tracking emissions for a task
tracker.start()

# Simulate a task
tracker.start_task("test")
for i in range(1000000):
    pass 
step_emissions = tracker.stop_task("test")

# Stop tracking emissions for the task
emissions = tracker.stop()

# Print the emissions data
print(f"Emissions for the step: {step_emissions} kg CO2")
print(f"Emissions for the task: {emissions} kg CO2")
```

On unix it runs through while on Windows 11 it fails:
```
[codecarbon INFO @ 22:42:03] [setup] RAM Tracking...
[codecarbon INFO @ 22:42:03] [setup] GPU Tracking...
[codecarbon INFO @ 22:42:03] No GPU found.
[codecarbon INFO @ 22:42:03] [setup] CPU Tracking...
[codecarbon WARNING @ 22:42:03] No CPU tracking mode found. Falling back on CPU constant mode.
[codecarbon WARNING @ 22:42:07] We saw that you have a 13th Gen Intel(R) Core(TM) i7-1365U but we don't know it. Please contact us.
[codecarbon INFO @ 22:42:07] CPU Model on constant consumption mode: 13th Gen Intel(R) Core(TM) i7-1365U
[codecarbon INFO @ 22:42:07] >>> Tracker's metadata:
[codecarbon INFO @ 22:42:07]   Platform system: Windows-10-10.0.22631-SP0
[codecarbon INFO @ 22:42:07]   Python version: 3.10.14
[codecarbon INFO @ 22:42:07]   CodeCarbon version: 2.5.0
[codecarbon INFO @ 22:42:07]   Available RAM : 15.347 GB
[codecarbon INFO @ 22:42:07]   CPU count: 12
[codecarbon INFO @ 22:42:07]   CPU model: 13th Gen Intel(R) Core(TM) i7-1365U
[codecarbon INFO @ 22:42:07]   GPU count: None
[codecarbon INFO @ 22:42:07]   GPU model: None
[codecarbon INFO @ 22:42:08] Saving emissions data to file c:\Users\Philipp\1_code\BP\pepperoni\emissions.csv
Traceback (most recent call last):
  File "c:\Users\Philipp\1_code\BP\pepperoni\test.py", line 13, in <module>
    tracker.start_task("test")
  File "C:\Users\Philipp\miniconda3\envs\f2c\lib\site-packages\codecarbon\emissions_tracker.py", line 484, in start_task
    _ = self._prepare_emissions_data()
  File "C:\Users\Philipp\miniconda3\envs\f2c\lib\site-packages\codecarbon\emissions_tracker.py", line 627, in _prepare_emissions_data
    emissions_rate=emissions / duration.seconds,  # kg/s
ZeroDivisionError: float division by zero
```

Here is another example adapted from the documentation on `start_task`:
```
from datasets import load_dataset
from codecarbon import EmissionsTracker

try:
    tracker = EmissionsTracker(project_name="bert_inference", measure_power_secs=10)
    tracker.start_task("load dataset")
    dataset = load_dataset("imdb", split="test")
    imdb_emissions = tracker.stop_task()
finally:
    _ = tracker.stop()
```

This is failing with the same error.

**Comment by philippkolbe** [comment]
When I look at the code it just seems like a bug... you are setting the `self._start_time` on initialization.
Then, in `prepare_emissions_data` immediately afterwards you are measuring the difference between the current time and the start_time - this seems to be 0 seconds. When you try to divide by that value it fails.

This might be how windows specific times work?
But I guess you should just check that you are not dividing by zero there.

**Comment by inimaz** [comment]
Hello @philippkolbe! 
Thanks for using `codecarbon`. Sorry for the inconvenience, this divide by zero issue, is a known issue that hopefully has been fixed (see #589 ) . It will be included in the next release of the package `2.5.1`. 

Keep an eye on the release PR to know if the package has been created ==> https://github.com/mlco2/codecarbon/pull/628
Have a nice day!

**Comment by philippkolbe** [comment]
@inimaz Thanks! Didn't find that one...

**Comment by inimaz** [comment]
@philippkolbe Version 2.5.1 is now available! Please try with that one and reopen this issue if needed.
